# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GriDot' do
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Firebase'
	pod 'FirebaseAuth'
	pod 'FirebaseStorage'
	pod 'FirebaseFunctions'
	pod 'RxGesture'
	
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GriDot

end
