# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
use_frameworks!

target 'myFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for myFirebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

end
